# Generated by Django 3.0.5 on 2020-05-11 04:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_auto_20200510_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textpost',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Posted on: '),
        ),
    ]
