# Generated by Django 3.0.5 on 2020-05-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_add_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='post_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='textpost',
            name='post_type',
            field=models.CharField(default='text', max_length=50),
        ),
    ]
