# Generated by Django 3.0.5 on 2020-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20200511_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='post_type',
            field=models.CharField(default='image', max_length=50),
        ),
    ]
